package pos.rebuild.v2.controller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import rojerusan.necesario.RSScrollBar;

//date and time
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Timer;

import java.util.Date;

/**
 *
 * @author John Brix Pomoy
 */
public class CashierController extends javax.swing.JFrame {

    /**
     * Creates new form Cashier_body
     */
    Connection con = null;

    public CashierController() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setUI(new RSScrollBar());
        jScrollPane2.getVerticalScrollBar().setUI(new RSScrollBar());
        //for print 
        jScrollPane3.getVerticalScrollBar().setUI(new RSScrollBar());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        orderprint = new javax.swing.JPanel();
        printbg = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        printTextArea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        qty_transfer = new javax.swing.JLabel();
        pcode_trans = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ids_transferr = new javax.swing.JLabel();
        usr_trans = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        product_name_trans = new javax.swing.JLabel();
        price_trans = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        categ_trans = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        exit_printer = new javax.swing.JLabel();
        background_ofPrint = new javax.swing.JLabel();
        backround = new javax.swing.JPanel();
        logout_function = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        CASHIER = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new rojerusan.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        listed = new rojerusan.RSTableMetro();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        avail_stock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalprice_txt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cash_ammount = new javax.swing.JTextField();
        logo_for_searchbar = new javax.swing.JLabel();
        sort = new javax.swing.JTextField();
        TotalChange = new javax.swing.JLabel();
        changebox = new javax.swing.JTextField();
        sumTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        cashier = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        body.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bodyPropertyChange(evt);
            }
        });
        body.setLayout(new java.awt.CardLayout());

        orderprint.setBackground(new java.awt.Color(255, 255, 255));
        orderprint.setPreferredSize(new java.awt.Dimension(900, 450));
        orderprint.setLayout(null);

        printbg.setBackground(new java.awt.Color(255, 255, 255));
        printbg.setPreferredSize(new java.awt.Dimension(360, 450));
        printbg.setLayout(null);

        printTextArea.setEditable(false);
        printTextArea.setColumns(20);
        printTextArea.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        printTextArea.setRows(5);
        printTextArea.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane3.setViewportView(printTextArea);

        printbg.add(jScrollPane3);
        jScrollPane3.setBounds(240, 10, 290, 400);

        jLabel14.setText("quantity");
        printbg.add(jLabel14);
        jLabel14.setBounds(100, 30, 45, 16);

        jLabel13.setText("pcode");
        printbg.add(jLabel13);
        jLabel13.setBounds(30, 30, 34, 16);

        qty_transfer.setBackground(new java.awt.Color(0, 153, 255));
        qty_transfer.setForeground(new java.awt.Color(255, 255, 255));
        qty_transfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_transfer.setOpaque(true);
        printbg.add(qty_transfer);
        qty_transfer.setBounds(90, 50, 50, 50);

        pcode_trans.setBackground(new java.awt.Color(0, 153, 255));
        pcode_trans.setForeground(new java.awt.Color(255, 255, 255));
        pcode_trans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pcode_trans.setOpaque(true);
        printbg.add(pcode_trans);
        pcode_trans.setBounds(30, 54, 50, 40);

        jLabel15.setText("ids");
        printbg.add(jLabel15);
        jLabel15.setBounds(30, 110, 40, 16);

        ids_transferr.setBackground(new java.awt.Color(51, 102, 255));
        ids_transferr.setOpaque(true);
        printbg.add(ids_transferr);
        ids_transferr.setBounds(30, 130, 50, 50);

        usr_trans.setBackground(new java.awt.Color(102, 102, 255));
        usr_trans.setOpaque(true);
        printbg.add(usr_trans);
        usr_trans.setBounds(90, 130, 50, 50);

        jLabel16.setText("users");
        printbg.add(jLabel16);
        jLabel16.setBounds(100, 110, 50, 20);

        product_name_trans.setOpaque(true);
        printbg.add(product_name_trans);
        product_name_trans.setBounds(90, 200, 100, 50);

        price_trans.setOpaque(true);
        printbg.add(price_trans);
        price_trans.setBounds(30, 200, 50, 50);

        jLabel12.setText("pname");
        printbg.add(jLabel12);
        jLabel12.setBounds(90, 180, 39, 16);

        jLabel11.setText("price");
        printbg.add(jLabel11);
        jLabel11.setBounds(30, 180, 28, 16);

        categ_trans.setOpaque(true);
        printbg.add(categ_trans);
        categ_trans.setBounds(30, 270, 100, 60);

        jLabel17.setText("categories");
        printbg.add(jLabel17);
        jLabel17.setBounds(30, 250, 60, 20);

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(0, 153, 255));
        rSMaterialButtonRectangle2.setText("PRINT");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        printbg.add(rSMaterialButtonRectangle2);
        rSMaterialButtonRectangle2.setBounds(590, 350, 140, 60);

        exit_printer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit_printer.setForeground(new java.awt.Color(255, 255, 255));
        exit_printer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_printer.setText("X");
        exit_printer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_printerMouseClicked(evt);
            }
        });
        printbg.add(exit_printer);
        exit_printer.setBounds(700, 0, 40, 30);

        background_ofPrint.setBackground(new java.awt.Color(255, 102, 102));
        background_ofPrint.setOpaque(true);
        printbg.add(background_ofPrint);
        background_ofPrint.setBounds(0, 0, 740, 420);

        orderprint.add(printbg);
        printbg.setBounds(-680, -270, 286, 398);

        body.add(orderprint, "card2");

        getContentPane().add(body);
        body.setBounds(185, 274, 739, 418);

        backround.setBackground(new java.awt.Color(33, 49, 64));
        backround.setFocusable(false);
        backround.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                backroundPropertyChange(evt);
            }
        });
        backround.setLayout(null);

        logout_function.setBackground(new java.awt.Color(255, 255, 255));
        logout_function.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        logout_function.setForeground(new java.awt.Color(204, 204, 204));
        logout_function.setText("Log-out");
        logout_function.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_functionMouseClicked(evt);
            }
        });
        backround.add(logout_function);
        logout_function.setBounds(1220, 40, 80, 40);

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        minimize.setForeground(new java.awt.Color(204, 204, 204));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A ICONS EXIT AND MINIMIZED/iconfinder_minus_circle_1303875.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        backround.add(minimize);
        minimize.setBounds(1240, 0, 40, 40);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A ICONS EXIT AND MINIMIZED/iconfinder_cancel_circle_1303876.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
        });
        backround.add(exit);
        exit.setBounds(1280, -10, 40, 60);

        CASHIER.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 40)); // NOI18N
        CASHIER.setForeground(new java.awt.Color(255, 255, 255));
        CASHIER.setText("Welcome Cashier!");
        backround.add(CASHIER);
        CASHIER.setBounds(20, 50, 770, 50);

        jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane1MouseWheelMoved(evt);
            }
        });

        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Category", "Price", "Available Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColorBackgoundHead(new java.awt.Color(209, 211, 212));
        table.setColorBordeFilas(new java.awt.Color(188, 190, 192));
        table.setColorBordeHead(new java.awt.Color(188, 190, 192));
        table.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        table.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        table.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        table.setColorSelBackgound(new java.awt.Color(147, 149, 152));
        table.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        table.setFuenteFilas(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        table.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        table.setFuenteHead(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(40);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tableMouseWheelMoved(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
        }

        backround.add(jScrollPane1);
        jScrollPane1.setBounds(20, 280, 590, 300);

        jScrollPane2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane2MouseWheelMoved(evt);
            }
        });

        listed.setForeground(new java.awt.Color(255, 255, 255));
        listed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Category", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listed.setColorBackgoundHead(new java.awt.Color(209, 211, 212));
        listed.setColorBordeFilas(new java.awt.Color(188, 190, 192));
        listed.setColorBordeHead(new java.awt.Color(188, 190, 192));
        listed.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        listed.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        listed.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        listed.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        listed.setColorSelBackgound(new java.awt.Color(147, 149, 152));
        listed.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        listed.setFuenteFilas(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        listed.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        listed.setFuenteHead(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        listed.setIntercellSpacing(new java.awt.Dimension(0, 0));
        listed.setRowHeight(40);
        listed.setShowHorizontalLines(false);
        listed.setShowVerticalLines(false);
        listed.getTableHeader().setReorderingAllowed(false);
        listed.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                listedMouseWheelMoved(evt);
            }
        });
        listed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listed);
        if (listed.getColumnModel().getColumnCount() > 0) {
            listed.getColumnModel().getColumn(0).setResizable(false);
            listed.getColumnModel().getColumn(1).setResizable(false);
            listed.getColumnModel().getColumn(2).setResizable(false);
            listed.getColumnModel().getColumn(3).setResizable(false);
            listed.getColumnModel().getColumn(4).setResizable(false);
            listed.getColumnModel().getColumn(5).setResizable(false);
        }

        backround.add(jScrollPane2);
        jScrollPane2.setBounds(700, 280, 600, 300);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText(">>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backround.add(jButton1);
        jButton1.setBounds(630, 410, 59, 25);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Stock:");
        backround.add(jLabel1);
        jLabel1.setBounds(20, 150, 140, 30);

        avail_stock.setEditable(false);
        avail_stock.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        backround.add(avail_stock);
        avail_stock.setBounds(160, 150, 220, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Code:");
        backround.add(jLabel2);
        jLabel2.setBounds(30, 110, 130, 30);

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        backround.add(ID);
        ID.setBounds(160, 110, 220, 30);

        pname.setEditable(false);
        pname.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        backround.add(pname);
        pname.setBounds(160, 190, 220, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category:");
        backround.add(jLabel3);
        jLabel3.setBounds(70, 230, 80, 30);

        category.setEditable(false);
        category.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        backround.add(category);
        category.setBounds(160, 230, 220, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QTY:");
        backround.add(jLabel5);
        jLabel5.setBounds(390, 150, 50, 30);

        Price.setEditable(false);
        Price.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });
        backround.add(Price);
        Price.setBounds(440, 110, 160, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price:");
        backround.add(jLabel6);
        jLabel6.setBounds(390, 110, 50, 30);

        totalprice_txt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        totalprice_txt.setText("Total Price :");
        backround.add(totalprice_txt);
        totalprice_txt.setBounds(710, 640, 110, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Cash:");
        backround.add(jLabel4);
        jLabel4.setBounds(700, 590, 140, 30);

        cash_ammount.setBackground(new java.awt.Color(33, 49, 64));
        cash_ammount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        cash_ammount.setForeground(new java.awt.Color(255, 255, 255));
        cash_ammount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        cash_ammount.setOpaque(false);
        cash_ammount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cash_ammountKeyReleased(evt);
            }
        });
        backround.add(cash_ammount);
        cash_ammount.setBounds(810, 590, 120, 30);

        logo_for_searchbar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        logo_for_searchbar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_for_searchbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ALTERED DESIGN/search bar/icons8-search-24.png"))); // NOI18N
        backround.add(logo_for_searchbar);
        logo_for_searchbar.setBounds(580, 230, 30, 40);

        sort.setEditable(false);
        sort.setBackground(new java.awt.Color(33, 49, 64));
        sort.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        sort.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sort.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        sort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortMouseClicked(evt);
            }
        });
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });
        backround.add(sort);
        sort.setBounds(400, 230, 180, 30);

        TotalChange.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        TotalChange.setText("Total Change:");
        backround.add(TotalChange);
        TotalChange.setBounds(960, 640, 120, 30);

        changebox.setEditable(false);
        changebox.setBackground(new java.awt.Color(255, 255, 153));
        changebox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        changebox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        changebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeboxActionPerformed(evt);
            }
        });
        backround.add(changebox);
        changebox.setBounds(950, 640, 230, 110);

        sumTotal.setEditable(false);
        sumTotal.setBackground(new java.awt.Color(204, 204, 204));
        sumTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        sumTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sumTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumTotalActionPerformed(evt);
            }
        });
        backround.add(sumTotal);
        sumTotal.setBounds(700, 640, 230, 110);

        jLabel8.setBackground(new java.awt.Color(0, 206, 209));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Insert Order");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        backround.add(jLabel8);
        jLabel8.setBounds(700, 230, 140, 40);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Clear");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        backround.add(jLabel9);
        jLabel9.setBounds(1000, 230, 140, 40);

        jLabel10.setBackground(new java.awt.Color(153, 153, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Undo Order");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        backround.add(jLabel10);
        jLabel10.setBounds(850, 230, 140, 40);

        qty.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        backround.add(qty);
        qty.setBounds(440, 150, 160, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product Name:");
        backround.add(jLabel7);
        jLabel7.setBounds(30, 190, 130, 30);

        jLabel21.setBackground(new java.awt.Color(204, 255, 255));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("PRINT");
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        backround.add(jLabel21);
        jLabel21.setBounds(1200, 600, 100, 150);

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 206, 209));
        rSMaterialButtonRectangle1.setText("Insert Order");
        rSMaterialButtonRectangle1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        backround.add(rSMaterialButtonRectangle1);
        rSMaterialButtonRectangle1.setBounds(700, 230, 140, 40);

        cashier.setEditable(false);
        backround.add(cashier);
        cashier.setBounds(860, 90, 100, 60);

        id.setEditable(false);
        backround.add(id);
        id.setBounds(970, 90, 100, 60);

        jLabel18.setBackground(new java.awt.Color(245, 176, 65));
        jLabel18.setText("jLabel1");
        jLabel18.setOpaque(true);
        backround.add(jLabel18);
        jLabel18.setBounds(-70, -6, 1400, 40);

        getContentPane().add(backround);
        backround.setBounds(0, 0, 1324, 762);

        setSize(new java.awt.Dimension(1324, 762));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane2MouseWheelMoved


    }//GEN-LAST:event_jScrollPane2MouseWheelMoved

    private void listedMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_listedMouseWheelMoved

    }//GEN-LAST:event_listedMouseWheelMoved

    private void jScrollPane1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseWheelMoved

    private void tableMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tableMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseWheelMoved

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked

        //fade
        for (double i = 1.0; i >= 0.0; i = i - 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(30);
            } catch (Exception e) {

            }
        }

        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void logout_functionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_functionMouseClicked

        JOptionPane.showMessageDialog(this, "Successfully Log-out!");

        LoginController a = new LoginController();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        dispose();

    }//GEN-LAST:event_logout_functionMouseClicked

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void changeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeboxActionPerformed

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortActionPerformed

    private void sumTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumTotalActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked


    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

    }//GEN-LAST:event_jLabel8MouseClicked

    private void cash_ammountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cash_ammountKeyReleased

    }//GEN-LAST:event_cash_ammountKeyReleased
    public void CasherMovedata(int index) {

    }
    private void listedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listedMouseClicked


    }//GEN-LAST:event_listedMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked


    }//GEN-LAST:event_jLabel10MouseClicked


    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked

        printTextArea.setText("");

        try {

            String id_user = id.getText();
            String users = cashier.getText();

            Float c = Float.parseFloat(changebox.getText());

            if (cash_ammount.getText().equals("")) {

                JOptionPane.showMessageDialog(rootPane, "Cash is empty or invalid output!");
            } else if (c < 0) {
                JOptionPane.showMessageDialog(rootPane, "Cash is not enough!");

            } else {

                String id_user2 = id.getText();
                String users2 = cashier.getText();

                int x = JOptionPane.showConfirmDialog(null, "Press Enter to continue.", "Confirm", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {

                    ids_transferr.setText(id_user2);
                    usr_trans.setText(users2);

                    printbg.setBackground(new Color(0, 0, 0, 93));

                    backround.removeAll();
                    backround.add(printbg);

                    body.removeAll();

                    body.add(printbg);
                    body.repaint();
                    body.revalidate();

                    body.setVisible(true);

                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jLabel21MouseClicked


    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed

        int x = JOptionPane.showConfirmDialog(null, "Do you want to print?", "Printing", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            try {

                printTextArea.print();

            } catch (Exception e) {

            }
        }


    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void exit_printerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_printerMouseClicked

        for (double i = 1.0; i >= 0.0; i = i - 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(10);
            } catch (Exception e) {

            }
        }
       
        String s = usr_trans.getText();
        String ids = ids_transferr.getText();

        CashierController a = new CashierController();

        CashierController.cashier.setText(s);
        CashierController.id.setText(ids);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        dispose();

       
    }//GEN-LAST:event_exit_printerMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void backroundPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_backroundPropertyChange

    }//GEN-LAST:event_backroundPropertyChange

    private void bodyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bodyPropertyChange

    }//GEN-LAST:event_bodyPropertyChange

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       
        body.setVisible(false);

    }//GEN-LAST:event_formPropertyChange

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    
    }//GEN-LAST:event_jLabel9MouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void sortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortMouseClicked
        JOptionPane.showMessageDialog(this, "We will this in System Innovation ");
    }//GEN-LAST:event_sortMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CASHIER;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Price;
    private javax.swing.JLabel TotalChange;
    private javax.swing.JTextField avail_stock;
    private javax.swing.JLabel background_ofPrint;
    private javax.swing.JPanel backround;
    private javax.swing.JPanel body;
    private javax.swing.JTextField cash_ammount;
    public static javax.swing.JTextField cashier;
    private javax.swing.JLabel categ_trans;
    private javax.swing.JTextField category;
    private javax.swing.JTextField changebox;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit_printer;
    public static javax.swing.JTextField id;
    private javax.swing.JLabel ids_transferr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSTableMetro listed;
    private javax.swing.JLabel logo_for_searchbar;
    private javax.swing.JLabel logout_function;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel orderprint;
    private javax.swing.JLabel pcode_trans;
    private javax.swing.JTextField pname;
    private javax.swing.JLabel price_trans;
    public static javax.swing.JTextArea printTextArea;
    private javax.swing.JPanel printbg;
    private javax.swing.JLabel product_name_trans;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel qty_transfer;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JTextField sort;
    private javax.swing.JTextField sumTotal;
    private rojerusan.RSTableMetro table;
    private javax.swing.JLabel totalprice_txt;
    private javax.swing.JLabel usr_trans;
    // End of variables declaration//GEN-END:variables
}
